version: '3.8'

services:
'''
  api:
    image: datascientest/fastapi:1.0.0
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - logs:/api_log
    networks:
      - test_network

  authentication_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication_test
    entrypoint: ["python", "/app/test_authentication.py"]
    depends_on:
      - api
    volumes:
      - scripts:/app
      - logs:/api_log
    networks:
      - test_network
    environment:
      LOG: "1"
 ''' 
  jm_neo4j:
    image : 5.26-community-bullseye
    container_name: jm_neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j  # Set the username and password for Neo4j
    volumes:
      - ../docker_vol/data_db/neo4j/csv:/var/lib/neo4j/import  # Mount the 'csv' folder to the Neo4j import directory
      - ../docker_vol/data_db/neo4j/dbfiles:/var/lib/neo4j/data  # Mount the database folder (optional, if you want to persist Neo4j data)
      - ../docker_vol/data_db/neo4j/script:/var/lib/neo4j/script  # Mount the folder containing your .cql script (optional)
    ports:
      - "7474:7474"  # HTTP port for Neo4j browser
      - "7687:7687"  # Bolt protocol port for client connections
    command: >
      bash -c "
        /var/lib/neo4j/bin/neo4j-admin load --from=/var/lib/neo4j/script/import_ESCO_csv_en.cql --database=neo4j --force && 
        /var/lib/neo4j/bin/neo4j console
      "
    networks:
      - jm_network
'''
  content_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content_test
    entrypoint: ["python", "/app/test_content.py"]
    depends_on:
      - authorization_test
    volumes:
      - scripts:/app
      - logs:/api_log
    networks:
      - test_network
    environment:
      LOG: "1"
'''
networks:
  jm_network:

volumes:
  scripts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./scripts

  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs